### ISSUE TITLE
UI Customization: adding custom image, rotate and stop at fixed angle range 

### ISSUE THREAD

**Issue by Abhishek9634** [sh-khashimov/SwiftFortuneWheel#1]
The circular image is coming from server
we need to add and rotation and set after certain rotations to particular angle range
how can we achieve that

**Comment by sh-khashimov** [comment]
if I understand you correctly, you want to add a new slice, and turn the wheel to the added slice?

**Comment by Abhishek9634** [comment]
Let me explain you

I will get Circular disc image from server.
I need to add that circular image rather than creating manually 8 different segments.
I want it to rotate and stop with animation to a particular angle.

**Comment by sh-khashimov** [comment]
You can create a segment dynamically when you receive your image from the server. Take a look at the example project, at the `ExampleViewController`, focus on `addPriceAction` method.

If you want a rotate to the particular segment or the angle, you can use available animation API: `startAnimating(finishIndex:Int = 0, _ completion:((Bool) -> Void)?)` or `startAnimating(rotationCompletionOffset:CGFloat = 0.0, _ completion:((Bool) -> Void)?)`. However, you should note that using animation API will first fully rotate a wheel, then stop at the specified place. Currently, it's a limitation. I will try to improve the animation API within a week or so.

If you need to rotate at the specified angle without full rotation, you have to modify the `SpinningWheelAnimator` class. Set `fullRotationsUntilFinish = 0` and at the same class `addRotationAnimation` method, `starTransformAnim.duration` time whatever you like. I hope it helps you. Let me know if you have further questions.

**Comment by Abhishek9634** [comment]
Yes I want stop at index after several full rotations to make it natural.
and I will check if that works :)

I have circular image like this, i want this too rotate.
Is that possible ?

<img width="287" alt="Screenshot 2020-06-15 at 1 04 05 PM" src="https://user-images.githubusercontent.com/10388287/84909263-17140f00-b0d3-11ea-8523-4214769f622f.png">

**Comment by sh-khashimov** [comment]
Yes, it's possible to rotate if you want to rotate a Wheel, not a pin arrow in the center.

I see your Fortune Wheel design, it will be impossible to draw exactly as you want.
However, Here is what you can do:

![84909263-17140f00-b0d3-11ea-8523-4214769f622f22](https://user-images.githubusercontent.com/1962380/84910565-74f32780-b0d0-11ea-92b2-d65a67f98996.png)

1 - You can add this border outside the `SwiftFortuneWheel`, however, it won't rotate.
2 - Not possible to add. Maybe I will add this feature later.
3 - You have to hide a `SpinButton` inside the `SwiftFortuneWheel`, and add over `SwiftFortuneWheel` your own Image, or add your pin image to `SpinButton`.

In `SwiftFortuneWheelConfiguration`, position of `PinImageViewPreferences` have to be set to `.top`.

**Comment by Abhishek9634** [comment]
Okay, I will check this.
A big thanks for the support :)

**Comment by sh-khashimov** [comment]
Hi, I hope you are doing well. I'm closing your issue.
If you still have questions, take a look at the example project, especially to VariousWheelSpikeViewController. This controller representing the wheel that similar to yours.
