### ISSUE TITLE
How to detect taps on slices?

### ISSUE THREAD

**Issue by frkncngz** [sh-khashimov/SwiftFortuneWheel#10]
How can we detect taps on the slices with their indexes? Any ideas or suggestions?

**Comment by sh-khashimov** [comment]
Unfortunately, you can't add a gesture recognizer for each slice to detect taps with their indexes, due to the fact that the wheel with all slices is one whole image.
The only solution I see is to add a gesture recognizer to WheelView and calculate the index by coordinates for finger tapping in the WheelView. But one must also take into account that the WheelLayer inside WheelView can be rotated, in this case, you need to offset the coordinates to calculate the index.

**Comment by frkncngz** [comment]
@sh-khashimov thanks a lot. I figured it out by adding a gesture recognizer to the wheel, calculated the angle to the center and did the math according to the slice count and the initial index.

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the great library. @frkncngz do you have any demo available for detect taps on the wheel then it will be helpful? @sh-khashimov do you have any demo available for a detect tap on the wheel?

**Comment by kishanbh** [comment]
@sh-khashimov  do you have any demo available for a detect tap on the slice of a wheel or built-in function in a library?

**Comment by sh-khashimov** [comment]
@kishanbh sorry, I haven't. I will try to add this feature in the near future.

**Comment by kishanbh** [comment]
@frkncngz can you share code snippet for how you get a slice on tap of the wheel then it will be helpful?

**Comment by frkncngz** [comment]
@kishanbh you can add a `UITapGestureRecognizer` to the wheel:
```
let gestureRecognizer = UITapGestureRecognizer()
fortuneWheel.addGestureRecognizer(gestureRecognizer)
```
and get the angle when the gesture recognizer got triggered:
```
let touch = gestureRecognizer.location(in: self.fortuneWheel)
let origin = CGPoint(x: self.fortuneWheel.frame.width / 2, y: self.fortuneWheel.frame.height / 2)
var angle = touch.angle(to: origin)
```

and use this angle to calculate the slice you are tapping. You may need to consider slice count and the initial slice index too.

**Comment by sh-khashimov** [comment]
@kishanbh contact with me by email, I can send you SwiftFortuneWheel project with a tap gesture support to detect selected index.
I need to make refactoring and testing, so it can take a couple of days more before I make a release.

**Comment by sh-khashimov** [comment]
added, how to use example available here: https://github.com/sh-khashimov/SwiftFortuneWheel/blob/master/Documentation/API_Overview.md

**Comment by kishanbh** [comment]
@sh-khashimov, @frkncngz thanks for the quick replay and your efforts. @frkncngz exactly I did the same as before your comment for tapGesture
