### ISSUE TITLE
startRotationAnimation completion issue

### ISSUE THREAD

**Issue by abcreationIT** [sh-khashimov/SwiftFortuneWheel#11]
I don't understand why ` func startRotationAnimation(finishIndex: Int, continuousRotationTime: Int, continuousRotationSpeed: CGFloat = 4, _ completion: ((Bool) -> Void)?)` is returning me always `false` and why the bool in completion it's returned before the wheel stops.

**Comment by sh-khashimov** [comment]
should be fixed in 1.3.1.
