### ISSUE TITLE
IB Designables issue 

### ISSUE THREAD

**Issue by DeepakpalMakeMyIdea** [sh-khashimov/SwiftFortuneWheel#15]
Error on console - Fail to render and update auto layout status for viewController(Tsg-HD-LBo): Failed to launch designable agent because tool was shutting down. check the console for a more detailed description and please file a bug report at feedbackassistant.com

on creating build  the archive of app. work fine in debug mode. Please check this issue 

Process:               IBDesignablesAgent-iOS [49639]
Path:                  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/IBDesignablesAgent-iOS
Identifier:            IBDesignablesAgent-iOS
Version:               12.3 (17703)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [28516]
Responsible:           SimulatorTrampoline [455]
User ID:               501

Date/Time:             2021-05-25 14:56:38.077 +0530
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        BFE8C29E-ACEE-3C30-748C-C5DF75B4B9C5

Time Awake Since Boot: 10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [49639]

Application Specific Information:
CoreSimulator 757.5 - Device: iPhone 12 mini (1DD1CAF0-0420-4DAD-8DD0-5CDCE573BC9C) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12 mini
SwiftFortuneWheel/SwiftFortuneWheel.swift: 17: 14: Fatal error: Use of unimplemented initializer 'init(frame:)' for class 'SwiftFortuneWheel.SwiftFortuneWheel'

**Comment by DeepakpalMakeMyIdea** [comment]
<img width="1361" alt="Screenshot 2021-05-25 at 7 59 39 PM" src="https://user-images.githubusercontent.com/70193279/119516086-129caf80-bd94-11eb-8a5d-94b487bf29a3.png">
![Uploading Screenshot 2021-05-25 at 8.00.00 PM.png…]()

**Comment by sh-khashimov** [comment]
It was a bad idea to implement IBDesignable since live rendering not possible without a configuration, I will remove IBDesignable in the future release and leave it with IBInspectables only. You can temporarily turn off live rendering here if you need to make an archive:
<img width="373" alt="Screen Shot 2021-05-26 at 10 04 37" src="https://user-images.githubusercontent.com/1962380/119605375-208d1780-be0a-11eb-9294-77c0d5ce653f.png">
