### ISSUE TITLE
Can we apply gradient color to Slice and apply gradient color for Slice's Text? is it possible with some customization?

### ISSUE THREAD

**Issue by kishanbh** [sh-khashimov/SwiftFortuneWheel#16]

**Comment by kishanbh** [comment]
Hi, can we apply gradient color to Slice and apply gradient color for Slice's Text? is it possible with some customization? 
Thanks for the library and thanks for the reply.

**Comment by sh-khashimov** [comment]
With some modification, it's possible to apple gradient color to Slice's background. I add this in the future release. However, if you need a fast solution, here is a file that updated for gradient:
![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 11 00 40](https://user-images.githubusercontent.com/1962380/120275108-42831000-c2ca-11eb-84f1-82e1076cdde3.png)

[SliceDrawing.swift.zip](https://github.com/sh-khashimov/SwiftFortuneWheel/files/6573758/SliceDrawing.swift.zip)

About Text gradient, unfortunately, there is no easy solution.

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the quick reply and thanks for the beautiful library. I Hope, in a future release, there is an option for gradient color for slice text

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the quick reply and thanks for the beautiful library. Can you provide some help or guidance for text gradient (like customization)? Any help would be appreciated.

**Comment by kishanbh** [comment]
@sh-khashimov can we set like marked gradient for a slice(like bottom circular white then gray as a slice radius)?
![wheel](https://user-images.githubusercontent.com/53965811/120516185-b584a780-c3ec-11eb-8a6b-96b4a1ef82a8.png)

**Comment by kishanbh** [comment]
@sh-khashimov can we set like marked gradient for a slice(like bottom circular white than gray as a slice radius) and apply the gradient color to some slices only? any modification for the slice's text gradient color?
![wheel](https://user-images.githubusercontent.com/53965811/120587928-e0561680-c453-11eb-91db-dce119f182a9.png)

**Comment by kishanbh** [comment]
> With some modification, it's possible to apple gradient color to Slice's background. I add this in the future release. However, if you need a fast solution, here is a file that updated for gradient:
> ![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 11 00 40](https://user-images.githubusercontent.com/1962380/120275108-42831000-c2ca-11eb-84f1-82e1076cdde3.png)
> 
> [SliceDrawing.swift.zip](https://github.com/sh-khashimov/SwiftFortuneWheel/files/6573758/SliceDrawing.swift.zip)
> 
> About Text gradient, unfortunately, there is no easy solution.

@sh-khashimov can we apply gradient-like marked **(radial gradient)** in the attached image for the slice and applying for some slice only not all slice in the wheel?
![wheel](https://user-images.githubusercontent.com/53965811/120597877-39797680-c463-11eb-873b-6d48930d155c.png)

**Comment by kishanbh** [comment]
@sh-khashimov can you help with an above point?

**Comment by kishanbh** [comment]
@sh-khashimov can you help with the above point? it will be helpful

**Comment by kishanbh** [comment]
@sh-khashimov do you have any suggestions or thoughts about radial gradient for slice then it will be helpful.

**Comment by kishanbh** [comment]
@sh-khashimov do you have any suggestions or thoughts about radial gradient for slice then it will be helpful.

**Comment by sh-khashimov** [comment]
change the code above that I gave you to:
``` swift
context.drawLinearGradient(
              gradient,
            start: CGPoint(x: path.boundingBox.minX, y: path.boundingBox.midY),
              end: CGPoint(x: path.boundingBox.maxX, y: path.boundingBox.midY),
            options: []
            )
        //MARK: - Gradient Color END
```

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the reply but it gives a gradient but from bottom to top like in between colors straight line I want radial like orange marked in the attached image is it possible?
![1](https://user-images.githubusercontent.com/53965811/120758214-2d5aeb00-c52f-11eb-8332-af2029ee0aff.png)

**Comment by sh-khashimov** [comment]
instead of `context.drawLinearGradient`:
``` swift
        context.drawRadialGradient(gradient,
                                   startCenter: center,
                                   startRadius: 0,
                                   endCenter: center,
                                   endRadius: radius,
                                   options: [])
```

**Comment by kishanbh** [comment]
@sh-khashimov got it, thanks for the reply and library. do you have any idea about the slice's text gradient or any file modification?

**Comment by sh-khashimov** [comment]
Unfortunately, no. Since gradient text is just an image inside the text, which adds complexity for already not an easy text processing inside the `SwiftFortuneWheel`. If you need to add a gradient text, my current advice, convert text to an image with gradient applied text, then add that image to your Slice.

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the replay and all your help. Hope, in future version, we have gradient color option for text also
