### ISSUE TITLE
Bridge UIViewControllerRepresentable SwiftUI

### ISSUE THREAD

**Issue by bjornkoemans** [sh-khashimov/SwiftFortuneWheel#22]
Is there currently any documentation on how to get the wheel implementation wrapped in an UIViewControllerRepresentable such that the package can be used in SwiftUI environments? I have tried to create a bridge myself and initializing a static wheel succeeded but did not manage to bridge the controls of the wheel. Thanks in advance!

**Comment by sh-khashimov** [comment]
I'm working on it. I will add a new example project in the coming days.

**Comment by bjornkoemans** [comment]
Perfect! Looking forward to it :) Thanks!

**Comment by sh-khashimov** [comment]
Added. If you have questions or specific cases that I have not covered in the SwiftFortuneWheelDemo-SwiftUI project, please let me know.

**Comment by bjornkoemans** [comment]
Thank you so much! Just tried it out and will be playing with it in the coming days.

**Comment by bjornkoemans** [comment]
Hi, sorry for the delay. It is working perfectly, only I wish to implement the .variousWheelPodiumConfiguration configuration in the SwiftUI View. Which extensions are needed for that and what should I pass onto the SFWView()? Thanks in advance!

**Comment by sh-khashimov** [comment]
Add `SFWConfiguration+VariousWheelPodium.swift` file to the project. In the `ViewModel` class change:
``` swift
@Published var wheelConfiguration: SFWConfiguration = .blackCyanColorsConfiguration
```
to
``` swift
@Published var wheelConfiguration: SFWConfiguration = .variousWheelPodiumConfiguration
```

**Comment by bjornkoemans** [comment]
@sh-khashimov Thanks for the quick reply. I had already tried that and just did again, but it does not seem to work for me :( Maybe I am missing something? I have copied over all assets as well. Do you have a clue what is happening?

![Simulator Screen Shot - iPhone 12 - 2022-02-08 at 09 06 31](https://user-images.githubusercontent.com/28259492/152944183-ed384f99-878d-4c71-982d-8c2a2ef3c978.png)

**Comment by bjornkoemans** [comment]
@sh-khashimov Sorry to bother, could you have a look?

**Comment by bjornkoemans** [comment]
@sh-khashimov Unfortunately, I have not been able to get it working with the solution you provided.
