### ISSUE TITLE
get selected value after rotation

### ISSUE THREAD

**Issue by prakashmaharjan** [sh-khashimov/SwiftFortuneWheel#23]
how to get the selected value after wheel is stopped.
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-07 at 14 10 58](https://user-images.githubusercontent.com/8100150/148514941-c992762f-fac8-4a91-a5eb-935f18a0089d.png)

**Comment by sh-khashimov** [comment]
Hi, Prakash.
Answer to your question is available on example project.

**Comment by AmaniTawalba** [comment]
> Hi, Prakash. Answer to your question is available on example project.

please where can I find it

**Comment by frankyxcs** [comment]
is not working ..the index is always false
