### ISSUE TITLE
Cannot build on Xcode 14: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by KevinQuisquater** [sh-khashimov/SwiftFortuneWheel#33]
Hi everyone, before working on a simple fix, just just wanted to check whether everyone is encountering this issue with Xcode 14?

Lines 128-131 of `SwiftFortuneWheel.swift`

``` swift
#if os(iOS)
    @available(iOS 10.0, iOSApplicationExtension 10.0, *)
    private(set) lazy var impactFeedbackgenerator = UIImpactFeedbackGenerator(style: .light)
#endif
```

Error: `Stored properties cannot be marked potentially unavailable with '@available'`

Other librairies have encountered the same issue, the fix is not too difficult.
Could someone confirm they have the same issue? Thanks.

**Comment by KevinQuisquater** [comment]
Example of a fix in another library:

https://github.com/pichillilorenzo/flutter_inappwebview/commit/06f87e81c4f55b7b251a149ec0db60442bb351c3

**Comment by ankitjain02** [comment]
@sh-khashimov I am still facing the same issue and i have taken the latest version of code. Can you please confirm if the fix is merged.

**Comment by sh-khashimov** [comment]
> @sh-khashimov I am still facing the same issue and i have taken the latest version of code. Can you please confirm if the fix is merged.

Yeah, it is. The code is there, using the Xcode 14.0 building without issue.
You should try to clean the cache.
