### ISSUE TITLE
Support UIImage object alongside named image from asset 

### ISSUE THREAD

**Issue by M-I-N** [sh-khashimov/SwiftFortuneWheel#5]
Firstly, thanks for this wonderful project. 

Up until now, you have implemented it for the image to be set from the `Assets.xcassets` folder. I'm in a state where I need to be able to set image from external input (like, downloaded image or composed image with the help of `UIGraphicsImageRenderer`). 

I think this should be a feature of your project which opens up possibilities for anyone in the future. 

I've created #4 and awaiting for your consideration.

**Comment by sh-khashimov** [comment]
Hello, it seems logical to me. Merge done, thank you for your contribution.
I will release new version a later today including your changes.
