### ISSUE TITLE
Oscillating pin image when it collides with any of the separator

### ISSUE THREAD

**Issue by M-I-N** [sh-khashimov/SwiftFortuneWheel#6]
Can the pin image be oscillated? 

Actually it should be like, **the pin image rotates +θ / -θ degrees (depending on the direction of wheel rotation) and move back to original immediately after the collision** imitating an **_oscillation_** effect. 

I think a better visualisation would be these screenshots: 
<img width="496" alt="Screenshot 2020-07-07 at 12 18 02 AM" src="https://user-images.githubusercontent.com/17010288/86627784-a9307880-bfea-11ea-858b-9a8dd4419ab7.png">
<img width="496" alt="Screenshot 2020-07-07 at 12 22 04 AM" src="https://user-images.githubusercontent.com/17010288/86627853-c36a5680-bfea-11ea-9504-6c208aab33f3.png">

**Comment by sh-khashimov** [comment]
Do you mean a similar effect like on [this project](https://github.com/hsilived/SpinWheel2) right? 
Need to think it over, because now the pin image is optional, as well as anchor images. Also if a collision effect must be done relative to an anchor, there can be zero or two anchors at the same time, the position of the anchor could be anywhere with vertical and radian offset.

**Comment by M-I-N** [comment]
> Do you mean a similar effect like on [this project](https://github.com/hsilived/SpinWheel2) right?

Yes, kind of. 

> Also if a collision effect must be done relative to an anchor, ...

Actually, I'm not interested for the anchor images. Can the collision effect be done relative to the separator between two slices? If yes, then I think your concern about _**"there can be zero or two anchors at the same time"**_ can be left aside. 

See this: 
<img width="496" alt="Screenshot 2020-07-07 at 12 18 02 AM 2" src="https://user-images.githubusercontent.com/17010288/86770064-ee4bbd80-c071-11ea-82d1-a31ab59444c3.png">

In my case I need to have the collision effect whenever the **Pin Image** is being passed through by the purple lines (separator line to be exact).

**Comment by sh-khashimov** [comment]
I will take into consideration this feature for future releases. Nevertheless, right now I can not announce the date when this will be done.

**Comment by M-I-N** [comment]
Okay. Great. 

But can you consider adding a call back for any collision between the **Pin** & **Separator**? 
So that I can take action from the client side and maybe mimic the oscillation effect from the client side. And also some other actions like playing a collision sound or do a vibration. 

#### Something like below will be extremely helpful for my case: 

```swift
public class SwiftFortuneWheel: UIControl { 
    . . .
    enum Rotation {
        case clockwise
        case counterClockwise
    }
    . . . 
    public var onCollisionWithSeparator: ((Rotation) -> Void)?
    . . . 
}
```

#### With that, I can use it at the client side like: 

```swift
fortuneWheel.onCollisionWithSeparator = { rotation in 
    // TODO: play a sound / vibrate
    // TODO: maybe implement a Pin image (added in the client side) collision 
}
```

---

If you don't think you can focus on this right now, can you please give me a head start for calculation of collision detection?

**Comment by sh-khashimov** [comment]
I don't mind if you start. 

Do you have any idea, besides animation and sound, can this closure be useful for something else, that doesn't relate to SwiftFortuneWheel itself?

In my opinion, it is better to implement these features, not on the client-side, but how a quick and temporary solution I don't mind.

**Comment by sh-khashimov** [comment]
Added: https://github.com/sh-khashimov/SwiftFortuneWheel/blob/master/Documentation/collision.md

**Comment by M-I-N** [comment]
@sh-khashimov you are the man! Thanks a ton for this added feature.
