### ISSUE TITLE
How to adjust indefinite spin speed

### ISSUE THREAD

**Issue by delucamike** [sh-khashimov/SwiftFortuneWheel#7]
First, thank you so much for this project. I have been waiting for something like this for years!

Could you tell me what the best way is to adjust the initial speed of the wheel when it is in the indefinite spin mode?

**Comment by sh-khashimov** [comment]
Unfortunately, there is no such as thing like accelerating and decelerating at any animation method.
However, you can try this solution:

``` Swift
extension SwiftFortuneWheel {
    func animate(withAcceleration acceleration: CGFloat, accelerationTimeInSecond: Int) {
        guard let animationDuration = CFTimeInterval(exactly: accelerationTimeInSecond*2) else { return }
        let fullRotationsUntilFinish = Int((15*acceleration).rounded(.down))
        self.startAnimating(finishIndex: 0, fullRotationsUntilFinish: fullRotationsUntilFinish, animationDuration: animationDuration, nil)
        let deadline = DispatchTime.now() + DispatchTimeInterval.seconds(accelerationTimeInSecond)
        DispatchQueue.main.asyncAfter(deadline: deadline) {
            self.startAnimating()
        }
    }
}
```

And in your `startAnimating` method:

```Swift
fortuneWheel.animate(withAcceleration: 30, accelerationTimeInSecond: 4)
```

Try to play with variables, please let me know if it helped you.
Sorry if I don't understand you correctly. If you mean just a rotation speed, I will add this to the next release.

**Comment by delucamike** [comment]
Ok thanks. I'll look for the rotation speed in the next release.

**Comment by sh-khashimov** [comment]
1.0.3 released.

**Comment by kishanbh** [comment]
@sh-khashimov How can we adjust the speed of rotation when the wheel is in indefinite speed mode?

**Comment by sh-khashimov** [comment]
@kishanbh 
``` Swift
let speed: CGFloat = 10
fortuneWheel.startContinuousRotationAnimation(with: speed)
```

**Comment by kishanbh** [comment]
@sh-khashimov thanks for the quick reply. Can we also adjust accelerating for the wheel? Because currently, I'm not seeing any difference if we increase or decrease the rotation speed.
