### ISSUE TITLE
Enhancement: Ability to make slice background from an image

### ISSUE THREAD

**Issue by delucamike** [sh-khashimov/SwiftFortuneWheel#8]
I would love the option to make the background of a slice come from an image rather than just setting it to a color.

**Comment by sh-khashimov** [comment]
Could you please share an example, what kind of image do you want to set to background, and how it should look at the slice.

**Comment by delucamike** [comment]
I want to do a pattern similar to this. I’d also like the ability to do the numbers vertical like that 
![693DC014-91A9-4D62-833C-F286D2BF1512](https://user-images.githubusercontent.com/7157794/87871023-17762300-c97b-11ea-86fb-7d3d5d1ccd8c.jpeg)

**Comment by sh-khashimov** [comment]
SwiftFortuneWheel supports vertical text.
I'm not sure, is it possible to create such a pattern with dynamic size.

**Comment by delucamike** [comment]
I would just use my own image that has the pattern, not create it in the code. So ideally the slice would have a UIImageView property that would be the width of the top of the slice and the height of the slice and you would just scale the image.

**Comment by sh-khashimov** [comment]
Please share your pattern image so I can play around and see what I can do, in a future enhancement.

**Comment by sh-khashimov** [comment]
To make text vertical as you want, currently, the solution is only using orientation as .horizontal with numbersOfLInes = 0, and your text should have a spacing, for example: "2 0 0 0 X". I will try to improve that in the future, adding support for \n and adding more options for lineBreakMode.

**Comment by delucamike** [comment]
Thank you! I really appreciate your work on this.
<img width="391" alt="gold_back" src="https://user-images.githubusercontent.com/7157794/87876436-11e20280-c9a6-11ea-99f7-89a333f08dc9.png">
<img width="391" alt="silver_back" src="https://user-images.githubusercontent.com/7157794/87876453-2a521d00-c9a6-11ea-8c2f-61891e56e592.png">
<img width="391" alt="pink_back" src="https://user-images.githubusercontent.com/7157794/87876470-448bfb00-c9a6-11ea-983d-5bbc2238e8c1.png">

**Comment by sh-khashimov** [comment]
I added the ability to specify a background image to Slice in version 1.1.1. 
You also can specify how do you want to draw the image by changing `fortuneWheel.configuration?.wheelPreferences.slicePreferences.backgroundImageContentMode`. Currently, there are two options, `scaleAspectFill` and `bottom`. The default value is `scaleAspectFill`, where the image size will be changed to fill the slice size. On the `bottom` content mode, the image will be drawn with original size at the bottom left position of the slice. 
I hope that will be enough for your background image needs :)

**Comment by delucamike** [comment]
Thanks! This looks great.
