### ISSUE TITLE
Finish index to be at pin image

### ISSUE THREAD

**Issue by oenama** [sh-khashimov/SwiftFortuneWheel#9]
How can we get the finished index to be at pin image if it was on top? 

any idea? 
@sh-khashimov

**Comment by oenama** [comment]
like in here I wanna get/print the prize ($200) on startAnimating - > finished 
![IMG_8753](https://user-images.githubusercontent.com/11976534/94117371-cd1a9200-fe54-11ea-9edc-ce70cc607f30.jpg)

@sh-khashimov

**Comment by sh-khashimov** [comment]
when you start rotation animation, you specify the finish index. 
Please, read the [API overview](https://github.com/sh-khashimov/SwiftFortuneWheel/blob/master/Documentation/API_Overview.md).

**Comment by oenama** [comment]
> when you start rotation animation, you specify the finish index.
> Please, read the [API overview](https://github.com/sh-khashimov/SwiftFortuneWheel/blob/master/Documentation/API_Overview.md).

I did, but how can I add the finished index at pin image position? or like if I wanted it to be random and still need to get the prize title at pin image position


@sh-khashimov 
from VariousWheelSimpleViewController.swift 

```
var finishIndex: Int {
        return Int.random(in: 0..<wheelControl.slices.count)
    }


   wheelControl.startAnimating(indefiniteRotationTimeInSeconds: 1, finishIndex: finishIndex) { (finished) in
            print(finished)
            if finished {
                print(self.finishIndex)
                /// --> here
                print(self.prizes[self.finishIndex]) 
            }
      }
```

**Comment by sh-khashimov** [comment]
Regardless of your pin position, if `configuration.wheelPreferences.startPosition` set to `.top`, your rotation animation will stop at specified `finishIndex`.
if `configuration.wheelPreferences.startPosition` set to `.top` and your pin also on the top position, rotation always stops at the top. (at the pin position)

code from `VariousWheelSimpleViewController.swift` won't work for you. `self.finishIndex` is a computed property, when you call `print(self.finishIndex)`, it will return a new random number.

**Comment by sh-khashimov** [comment]
try this:

``` Swift
let _finishIndex = self.finishIndex
wheelControl.startAnimating(indefiniteRotationTimeInSeconds: 1, finishIndex: _finishIndex) { (finished) in
            print(finished)
            if finished {
                print(_finishIndex)
                /// --> here
                print(self.prizes[_finishIndex]) 
            }
      }
```

**Comment by oenama** [comment]
> Regardless of your pin position, if `configuration.wheelPreferences.startPosition` set to `.top`, your rotation animation will stop at specified `finishIndex`.
> if `configuration.wheelPreferences.startPosition` set to `.top` and your pin also on the top position, rotation always stops at the top. (at the pin position)
> 
> code from `VariousWheelSimpleViewController.swift` won't work for you. `self.finishIndex` is a computed property, when you call `print(self.finishIndex)`, it will return a new random number.

I completely missed that, Thank you for your help
